server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Fix "Request Header Or Cookie Too Large"
    large_client_header_buffers 4 32k;
    client_header_buffer_size 16k;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # SPA routing — toutes les routes vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Health check nginx
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # Cache assets statiques
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
